name: platform_target_dart_only
description: Factory-compatible Flutter seed project.
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  shared_preferences_android:
    path: third_party/shared_preferences_android
